### PR TITLE
Updates for New Tiles

### PR DESCRIPTION
**Pull request by jamesmcclain**
The Conus Albers CRS has been added and the code has been upgraded to a later version of Geotrellis.

Connects #11

**To Test**
1. Apply the following diff (preferably on top of https://github.com/WikiWatershed/model-my-watershed/pull/973):

``` diff
diff --git a/src/mmw/mmw/settings/base.py b/src/mmw/mmw/settings/base.py
index be2fcca..b724ebe 100644
--- a/src/mmw/mmw/settings/base.py
+++ b/src/mmw/mmw/settings/base.py
@@ -365,11 +365,11 @@ GEOP = {
     'request': {
         'input': {
             'geometry': None,
-            'tileCRS': 'WebMercator',
+            'tileCRS': 'ConusAlbers',
             'polyCRS': 'LatLng',
-            'nlcdLayer': 'nlcd-wm-ext-tms',
-            'soilLayer': 'soil-fake',
-            'zoom': 11
+            'nlcdLayer': 'nlcd-10m-epsg5070',
+            'soilLayer': 'ssurgo-soil-groups-10m',
+            'zoom': 0
         }
     }
 }
```
1. scp the new geoprocessing jar file onto the worker VM: `scp ./summary/target/scala-2.10/mmw-geoprocessing-assembly-0.2.0.jar vagrant@33.33.34.20:`
2. Overwrite the old geoprocessing jar file with the new one.  There are two jars to be overwritten, they can be found by typing `find /opt | grep geoprocessing | grep jar$` on the worker VM.
3. Reload the worker VM
4. Use the application

Works on areas with valid soil data (screenshot is from somewhere in Maine)
screenshot from 2015-10-21 16 32 38

Also works on areas without valid soil data by assuming Type B:
screenshot from 2015-10-21 16 41 48

**Limitations**

The TR-55 code assumes soil type A-D, but the soil rasters contain double-types AD, BD, and CD.  If you try to advance past the analyze page, the app will fail.

### CODE REVIEW

**Comment by mmcfarland** [comment]
Running into some vagrant issues with my worker box while testing this...still checking it out.

**Comment by mmcfarland** [comment]
+1, works great.

**Comment by mmcfarland** [comment]
Nice to see some real soil in there.

**Comment by jamesmcclain** [comment]
Agreed.  Thanks for reviewing.  I shall merge ...

**Pull request merged**
